init = ->
  projection = new (ol.proj.Projection)(
    code: 'EPSG:3857'
    units: 'm')
  vect = new (ol.layer.Image)(source: new (ol.source.ImageWMS)(
    url: 'http://g.osgeo.cn/cgi-bin/mapserv?map=/opt/mapws/mapfile/sheng.map'
    params:
      'LAYERS': 'sheng'
      'FORMAT': 'image/png'
    serverType: 'mapserver'))
  vect2 = new (ol.layer.Image)(
    extent: [
      7458000
      447000
      15846608
      8835608
    ]
    source: new (ol.source.ImageWMS)(
      url: 'http://g.osgeo.cn/cgi-bin/tilecache.cgi?'
      params:
        'LAYERS': 'china'
        'TILED': true
        'CRS': 'EPSG:3857'
        'WIDTH': '800'
        'HEIGHT': '500'
        'FORMAT': 'image/png'
      serverType: 'tilecache'))
  river = new (ol.layer.Image)(source: new (ol.source.ImageWMS)(
    url: 'http://g.osgeo.cn/cgi-bin/mapserv?map=/opt/mapws/mapfile/sheng.map'
    params:
      'LAYERS': 'river'
      'FORMAT': 'image/png'
    serverType: 'mapserver'))
  layers = [
    vect
    river
  ]
  # var layers = [];
  map = new (ol.Map)(
    layers: layers
    target: 'map'
    view: new (ol.View)(
      projection: projection
      center: ol.proj.transform([
        105
        38
      ], 'EPSG:4326', 'EPSG:3857')
      zoom: 3))
  #添加比例尺，单位m
  scaleLineControl = new (ol.control.ScaleLine)
  scaleLineControl.setUnits ol.control.UNIT_METER
  map.addControl scaleLineControl
  #缩放工具条
  zoomSilder = new (ol.control.ZoomSlider)
  map.addControl zoomSilder
  return

$(document).ready ->
  init()
  return

# ---
# generated by js2coffee 2.0.1