###*
# Created by bukun on 2015/2/21.
###

this.init = ->
  controls = [
    new (ol.control.Attribution)
    new (ol.control.MousePosition)(
      undefinedHTML: 'outside'
      projection: 'EPSG:4326'
      coordinateFormat: (coordinate) ->
        ol.coordinate.format coordinate, '{x}, {y}', 4
)
    # new (ol.control.OverviewMap)(collapsed: false)
    # new (ol.control.Rotate)(autoHide: false)
    # new (ol.control.ScaleLine)
    new (ol.control.Zoom)
    # new (ol.control.ZoomSlider)
    # new (ol.control.ZoomToExtent)
    # new (ol.control.FullScreen)
  ]
  projection = new (ol.proj.Projection)(
    code: 'EPSG:3857'
    units: 'm')
  base1 = new (ol.layer.Tile)(source: new (ol.source.MapQuest)(layer: 'osm'))
  vect = new (ol.layer.Image)(source: new (ol.source.ImageWMS)(
    url: 'http://g.osgeo.cn/shihang'
    params:
      'LAYERS': 'sheng'
      'FORMAT': 'image/png'
    serverType: 'mapserver'))
  maize = new (ol.layer.Image)(source: new (ol.source.ImageWMS)(
    url: 'http://g.osgeo.cn/shihang'
    params:
      'LAYERS': 'maize'
      'FORMAT': 'image/png'
    serverType: 'mapserver'))
  shucai_source = new (ol.source.ImageWMS)(
    url: 'http://g.osgeo.cn/shihang'
    params:
      'LAYERS': 'shucai'
      'FORMAT': 'image/png'
    serverType: 'mapserver')
  shucai = new (ol.layer.Image)(source: shucai_source)

  vect2 = new (ol.layer.Image)(
    extent: [
      7458000
      447000
      15846608
      8835608
    ]
    source: new (ol.source.ImageWMS)(
      url: 'http://g.osgeo.cn/cgi-bin/tilecache.cgi?'
      params:
        'LAYERS': 'china'
        'TILED': true
        'CRS': 'EPSG:3857'
        'WIDTH': '800'
        'HEIGHT': '500'
        'FORMAT': 'image/png'
      serverType: 'tilecache'))

  layers = [
    vect
    maize
    shucai
  ]
  # var layers = [vect2];
  attribution = new (ol.control.Attribution)(
    collapsible: true
    label: 'A'
    collapsed: true
    tipLabel: 'yooo')
  view = new (ol.View)(
    projection: projection
    center: ol.proj.transform([
      126
      44
    ], 'EPSG:4326', 'EPSG:3857')
    zoom: 6)
  map = new (ol.Map)(
    layers: layers
    target: 'map'
    # controls: controls
    view: view)
  map.on 'singleclick', (evt) ->
    document.getElementById('info').innerHTML = ''
    viewResolution = view.getResolution()
    # alert(viewResolution);
    url = shucai_source.getGetFeatureInfoUrl(evt.coordinate, viewResolution, 'EPSG:3857', 'INFO_FORMAT': 'text/html')
    # alert(url);
    if url
      document.getElementById('info').innerHTML = '<iframe seamless src="' + url + '"></iframe>'
    return
  #添加比例尺，单位m
  scaleLineControl = new (ol.control.ScaleLine)
  scaleLineControl.setUnits ol.control.UNIT_METER
  map.addControl scaleLineControl
  #缩放工具条
  zoomSilder = new (ol.control.ZoomSlider)
  map.addControl zoomSilder
  return

$(document).ready ->
  init()
  return

# ---
# generated by js2coffee 2.0.1